import { buttonStyles, cardStyles, layoutStyles, modalStyles, textStyles } from '../styles'

export const scoreboardStyles = {
  container: 'mx-auto space-y-2 pb-36',
  topBar: layoutStyles.rowEnd,
  iconButton: buttonStyles.iconBase,
  iconButtonGray: buttonStyles.iconGray,
  iconButtonAmber: buttonStyles.iconAmber,
  iconButtonDisabled: buttonStyles.iconDisabled,
  chartCard: cardStyles.sectionMd,
  quickTypeSection: 'bg-gray-900/95 rounded-2xl px-2 py-2',
  quickTypeHeader: 'hidden',
  quickTypeTitle: textStyles.titleSm,
  quickTypeList: 'grid grid-cols-5 gap-1',
  quickTypeButton: 'flex items-center justify-center rounded-lg px-1 py-3 transition',
  quickTypeButtonActive: 'bg-cyan-600 text-white',
  quickTypeButtonIdle: 'bg-gray-700 text-gray-200 hover:bg-gray-600',
  quickTypeIcon: 'text-2xl leading-none',
  playerList: 'flex flex-col gap-2',
  playerRow: 'relative',
  playerButton: 'w-full rounded-lg p-3 pr-12 transition',
  playerButtonIdle: 'ring-1 ring-transparent scale-100',
  playerButtonSelected: 'ring-2 ring-cyan-300 scale-[1.02] shadow-lg shadow-cyan-500/20',
  playerDetailButton: 'absolute top-2 right-2 rounded-full w-10 h-10 flex items-center justify-center bg-gray-900/70 text-white text-lg hover:bg-gray-700 transition',
  playerScoreRow: layoutStyles.rowBetween,
  playerScoreValue: textStyles.bold,
  quickActions: 'flex gap-1',
  quickAddButton: 'rounded-lg px-3 py-2 bg-green-700 hover:bg-green-600 text-white font-bold transition',
  quickInputButton: 'rounded-lg px-2 py-2 bg-gray-700 hover:bg-gray-600 text-white transition',
  bottomDock: 'fixed bottom-0 left-0 right-0 z-40 px-2 pb-[calc(0.5rem+env(safe-area-inset-bottom))] pt-2 bg-gradient-to-t from-gray-950 via-gray-950/95 to-transparent',
  dockPanel: 'mx-auto w-full max-w-2xl rounded-2xl border border-gray-700 bg-gray-900/95 p-2 backdrop-blur',
  dockActions: 'grid grid-cols-4 gap-2 mt-2',
  dockActionButton: 'rounded-xl py-3 text-base font-bold text-white transition',
  dockActionPositive: 'bg-green-700 hover:bg-green-600',
  dockActionNegative: 'bg-red-700 hover:bg-red-600',
  dockActionUndo: 'bg-gray-700 hover:bg-gray-600',
  dockActionDisabled: 'opacity-40 cursor-not-allowed',
  addScoreButton: buttonStyles.addScore,
  modalPrimary: modalStyles.primary,
  modalSecondary: modalStyles.secondary,
} as const
